version: "3"
services:
  postgres:
    image: 'postgres:11.5'
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=isaiasiotti"
      - "POSTGRES_DB=nestjsgraphql"
      - "POSTGRES_PASSWORD=Kero963,"